Neos:
  Neos:
    fusion:
      autoInclude:
        'Sitegeist.MoveAlong': true

  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            matchingStatusCodes: [ 403, 404, 410 ]
            options:
              viewClassName: \Sitegeist\MoveAlong\Error\FusionExceptionView
